skip_tags: true
image: Visual Studio 2019 Preview
environment:  
  BENCHMARKS: on  
  signingkey:
    secure: DcEnjxct82WwrppME28Rkw==

install:
  - cmd: choco install gitversion.portable --version 5.0.1 -y
  #- ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt DotNet.Glob.snk.enc -secret %signingkey%
  - cmd: choco install dotnetcore-sdk --pre

before_build:
  - ps: gitversion /l console /output buildserver

build:
  verbosity: detailed
build_script:
- cmd: dotnet restore ./src/DotNetGlob.sln --disable-parallel
- cmd: dotnet build ./src/DotNetGlob.sln -c Release --disable-parallel
- cmd: dotnet pack ./src/DotNetGlob.sln -c Release --output %APPVEYOR_BUILD_FOLDER%/artifacts/
test_script:
- cmd: dotnet test src/dotnet.glob.tests/dotnet.glob.tests.csproj
artifacts:
- path: artifacts/*
deploy:
  provider: NuGet
  api_key:
    secure: u8JpW5kkti8pMi+ra2QcXTJPhkHCA8pkKSiiZOJbcS/vFVHNvF3W8qw1Fy2If6a7
  skip_symbols: false
  artifact: /.*\.nupkg/